// Extra map packs
const WORLD_TERR = [
  {abbr:"AF",name:"Afghanistan"},
  {abbr:"AL",name:"Albania"},
  {abbr:"AE",name:"United Arab Emirates"},
  {abbr:"AM",name:"Armenia"},
  {abbr:"AT",name:"Austria"},
  {abbr:"BI",name:"Burundi"},
  {abbr:"BE",name:"Belgium"},
  {abbr:"BJ",name:"Benin"},
  {abbr:"BF",name:"Burkina Faso"},
  {abbr:"BD",name:"Bangladesh"},
  {abbr:"BG",name:"Bulgaria"},
  {abbr:"BA",name:"Bosnia and Herzegovina"},
  {abbr:"BY",name:"Belarus"},
  {abbr:"BZ",name:"Belize"},
  {abbr:"BO",name:"Bolivia"},
  {abbr:"BR",name:"Brazil"},
  {abbr:"BN",name:"Brunei Darussalam"},
  {abbr:"BT",name:"Bhutan"},
  {abbr:"BW",name:"Botswana"},
  {abbr:"CF",name:"Central African Republic"},
  {abbr:"CH",name:"Switzerland"},
  {abbr:"CI",name:"C\u00f4te d'Ivoire"},
  {abbr:"CM",name:"Cameroon"},
  {abbr:"CD",name:"Democratic Republic of the Congo"},
  {abbr:"CG",name:"Republic of Congo"},
  {abbr:"CO",name:"Colombia"},
  {abbr:"CR",name:"Costa Rica"},
  {abbr:"CU",name:"Cuba"},
  {abbr:"CZ",name:"Czech Republic"},
  {abbr:"DE",name:"Germany"},
  {abbr:"DJ",name:"Djibouti"},
  {abbr:"DO",name:"Dominican Republic"},
  {abbr:"DZ",name:"Algeria"},
  {abbr:"EC",name:"Ecuador"},
  {abbr:"EG",name:"Egypt"},
  {abbr:"ER",name:"Eritrea"},
  {abbr:"EE",name:"Estonia"},
  {abbr:"ET",name:"Ethiopia"},
  {abbr:"FI",name:"Finland"},
  {abbr:"GA",name:"Gabon"},
  {abbr:"GE",name:"Georgia"},
  {abbr:"GH",name:"Ghana"},
  {abbr:"GN",name:"Guinea"},
  {abbr:"GM",name:"The Gambia"},
  {abbr:"GW",name:"Guinea-Bissau"},
  {abbr:"GQ",name:"Equatorial Guinea"},
  {abbr:"GL",name:"Greenland"},
  {abbr:"GT",name:"Guatemala"},
  {abbr:"GY",name:"Guyana"},
  {abbr:"HN",name:"Honduras"},
  {abbr:"HR",name:"Croatia"},
  {abbr:"HT",name:"Haiti"},
  {abbr:"HU",name:"Hungary"},
  {abbr:"IN",name:"India"},
  {abbr:"IE",name:"Ireland"},
  {abbr:"IR",name:"Iran"},
  {abbr:"IQ",name:"Iraq"},
  {abbr:"IS",name:"Iceland"},
  {abbr:"IL",name:"Israel"},
  {abbr:"JM",name:"Jamaica"},
  {abbr:"JO",name:"Jordan"},
  {abbr:"KZ",name:"Kazakhstan"},
  {abbr:"KE",name:"Kenya"},
  {abbr:"KG",name:"Kyrgyzstan"},
  {abbr:"KH",name:"Cambodia"},
  {abbr:"KR",name:"Republic of Korea"},
  {abbr:"KW",name:"Kuwait"},
  {abbr:"LA",name:"Lao PDR"},
  {abbr:"LB",name:"Lebanon"},
  {abbr:"LR",name:"Liberia"},
  {abbr:"LY",name:"Libya"},
  {abbr:"LK",name:"Sri Lanka"},
  {abbr:"LS",name:"Lesotho"},
  {abbr:"LT",name:"Lithuania"},
  {abbr:"LU",name:"Luxembourg"},
  {abbr:"LV",name:"Latvia"},
  {abbr:"MA",name:"Morocco"},
  {abbr:"MD",name:"Moldova"},
  {abbr:"MG",name:"Madagascar"},
  {abbr:"MX",name:"Mexico"},
  {abbr:"MK",name:"Macedonia"},
  {abbr:"ML",name:"Mali"},
  {abbr:"MM",name:"Myanmar"},
  {abbr:"ME",name:"Montenegro"},
  {abbr:"MN",name:"Mongolia"},
  {abbr:"MZ",name:"Mozambique"},
  {abbr:"MR",name:"Mauritania"},
  {abbr:"MW",name:"Malawi"},
  {abbr:"NA",name:"Namibia"},
  {abbr:"NE",name:"Niger"},
  {abbr:"NG",name:"Nigeria"},
  {abbr:"NI",name:"Nicaragua"},
  {abbr:"NP",name:"Nepal"},
  {abbr:"PK",name:"Pakistan"},
  {abbr:"PA",name:"Panama"},
  {abbr:"PE",name:"Peru"},
  {abbr:"PL",name:"Poland"},
  {abbr:"KP",name:"Dem. Rep. Korea"},
  {abbr:"PY",name:"Paraguay"},
  {abbr:"PS",name:"Palestine"},
  {abbr:"QA",name:"Qatar"},
  {abbr:"RO",name:"Romania"},
  {abbr:"RW",name:"Rwanda"},
  {abbr:"EH",name:"Western Sahara"},
  {abbr:"SA",name:"Saudi Arabia"},
  {abbr:"SD",name:"Sudan"},
  {abbr:"SS",name:"South Sudan"},
  {abbr:"SN",name:"Senegal"},
  {abbr:"SL",name:"Sierra Leone"},
  {abbr:"SV",name:"El Salvador"},
  {abbr:"RS",name:"Serbia"},
  {abbr:"SR",name:"Suriname"},
  {abbr:"SK",name:"Slovakia"},
  {abbr:"SI",name:"Slovenia"},
  {abbr:"SE",name:"Sweden"},
  {abbr:"SZ",name:"Swaziland"},
  {abbr:"SY",name:"Syria"},
  {abbr:"TD",name:"Chad"},
  {abbr:"TG",name:"Togo"},
  {abbr:"TH",name:"Thailand"},
  {abbr:"TJ",name:"Tajikistan"},
  {abbr:"TM",name:"Turkmenistan"},
  {abbr:"TL",name:"Timor-Leste"},
  {abbr:"TN",name:"Tunisia"},
  {abbr:"TW",name:"Taiwan"},
  {abbr:"TZ",name:"Tanzania"},
  {abbr:"UG",name:"Uganda"},
  {abbr:"UA",name:"Ukraine"},
  {abbr:"UY",name:"Uruguay"},
  {abbr:"UZ",name:"Uzbekistan"},
  {abbr:"VE",name:"Venezuela"},
  {abbr:"VN",name:"Vietnam"},
  {abbr:"YE",name:"Yemen"},
  {abbr:"ZM",name:"Zambia"},
  {abbr:"ZW",name:"Zimbabwe"},
  {abbr:"SO",name:"Somalia"},
  {abbr:"XK",name:"Kosovo"},
  {abbr:"ZA",name:"South Africa"},
  {abbr:"NL",name:"Netherlands"},
  {abbr:"PT",name:"Portugal"},
  {abbr:"ES",name:"Spain"},
  {abbr:"GF",name:"French Guiana"},
  {abbr:"AW",name:"Aruba"},
  {abbr:"AI",name:"Anguilla"},
  {abbr:"BH",name:"Bahrain"},
  {abbr:"BL",name:"Saint-Barth\u00e9lemy"},
  {abbr:"BM",name:"Bermuda"},
  {abbr:"BB",name:"Barbados"},
  {abbr:"CW",name:"Cura\u00e7ao"},
  {abbr:"DM",name:"Dominica"},
  {abbr:"GD",name:"Grenada"},
  {abbr:"GU",name:"Guam"},
  {abbr:"LC",name:"Saint Lucia"},
  {abbr:"MF",name:"Saint-Martin"},
  {abbr:"MV",name:"Maldives"},
  {abbr:"MH",name:"Marshall Islands"},
  {abbr:"MS",name:"Montserrat"},
  {abbr:"NR",name:"Nauru"},
  {abbr:"PW",name:"Palau"},
  {abbr:"SX",name:"Sint Maarten"},
  {abbr:"TV",name:"Tuvalu"},
  {abbr:"VC",name:"Saint Vincent and the Grenadines"},
  {abbr:"VG",name:"British Virgin Islands"},
  {abbr:"BQBO",name:"Netherlands"},
  {abbr:"BQSE",name:"St. Eustatius (Netherlands)"},
  {abbr:"BQSA",name:"Saba (Netherlands)"},
  {abbr:"MQ",name:"Martinique"},
  {abbr:"YT",name:"Mayotte"},
  {abbr:"RE",name:"Reunion"},
  {abbr:"US",name:"United States"},
  {abbr:"RU",name:"Russia"},
  {abbr:"AU",name:"Australia"},
  {abbr:"CA",name:"Canada"},
  {abbr:"CN",name:"China"},
  {abbr:"JP",name:"Japan"},
  {abbr:"GB",name:"United Kingdom"},
  {abbr:"FR",name:"France"},
  {abbr:"IT",name:"Italy"}
];
const EUROPE_TERR = [
  {abbr:"AL",name:"Albania"},
  {abbr:"AD",name:"Andorra"},
  {abbr:"AM",name:"Armenia"},
  {abbr:"AT",name:"Austria"},
  {abbr:"BE",name:"Belgium"},
  {abbr:"BG",name:"Bulgaria"},
  {abbr:"BA",name:"Bosnia and Herzegovina"},
  {abbr:"BY",name:"Belarus"},
  {abbr:"CH",name:"Switzerland"},
  {abbr:"CZ",name:"Czech Republic"},
  {abbr:"DE",name:"Germany"},
  {abbr:"DK",name:"Denmark"},
  {abbr:"EE",name:"Estonia"},
  {abbr:"FI",name:"Finland"},
  {abbr:"GB",name:"United Kingdom"},
  {abbr:"GE",name:"Georgia"},
  {abbr:"GR",name:"Greece"},
  {abbr:"HR",name:"Croatia"},
  {abbr:"HU",name:"Hungary"},
  {abbr:"IE",name:"Ireland"},
  {abbr:"IS",name:"Iceland"},
  {abbr:"IT",name:"Italy"},
  {abbr:"LI",name:"Liechtenstein"},
  {abbr:"LT",name:"Lithuania"},
  {abbr:"LU",name:"Luxembourg"},
  {abbr:"LV",name:"Latvia"},
  {abbr:"MD",name:"Moldova"},
  {abbr:"MK",name:"Macedonia"},
  {abbr:"ME",name:"Montenegro"},
  {abbr:"NO",name:"Norway"},
  {abbr:"PL",name:"Poland"},
  {abbr:"PT",name:"Portugal"},
  {abbr:"RO",name:"Romania"},
  {abbr:"RS",name:"Serbia"},
  {abbr:"SK",name:"Slovakia"},
  {abbr:"SI",name:"Slovenia"},
  {abbr:"SE",name:"Sweden"},
  {abbr:"TR",name:"Turkey"},
  {abbr:"UA",name:"Ukraine"},
  {abbr:"XK",name:"Kosovo"},
  {abbr:"NL",name:"Netherlands"},
  {abbr:"ES",name:"Spain"},
  {abbr:"FR",name:"France"},
  {abbr:"CY",name:"Cyprus"}
];
const NA_TERR = [
  {abbr:"MB",name:"Manitoba"},
  {abbr:"SK",name:"Saskatchewan"},
  {abbr:"AB",name:"Alberta"},
  {abbr:"BC",name:"British Columbia"},
  {abbr:"NU",name:"Nunavut"},
  {abbr:"NT",name:"Northwest Territories"},
  {abbr:"YT",name:"Yukon"},
  {abbr:"ON",name:"Ontario"},
  {abbr:"QC",name:"Qu\u00e9bec"},
  {abbr:"NB",name:"New Brunswick"},
  {abbr:"NS",name:"Nova Scotia"},
  {abbr:"NL",name:"Newfoundland and Labrador"},
  {abbr:"PE",name:"Prince Edward Island"},
  {abbr:"MA",name:"Massachusetts"},
  {abbr:"MN",name:"Minnesota"},
  {abbr:"MT",name:"Montana"},
  {abbr:"ND",name:"North Dakota"},
  {abbr:"HI",name:"Hawaii"},
  {abbr:"ID",name:"Idaho"},
  {abbr:"WA",name:"Washington"},
  {abbr:"AZ",name:"Arizona"},
  {abbr:"CA",name:"California"},
  {abbr:"CO",name:"Colorado"},
  {abbr:"NV",name:"Nevada"},
  {abbr:"NM",name:"New Mexico"},
  {abbr:"OR",name:"Oregon"},
  {abbr:"UT",name:"Utah"},
  {abbr:"WY",name:"Wyoming"},
  {abbr:"AR",name:"Arkansas"},
  {abbr:"IA",name:"Iowa"},
  {abbr:"KS",name:"Kansas"},
  {abbr:"MO",name:"Missouri"},
  {abbr:"NE",name:"Nebraska"},
  {abbr:"OK",name:"Oklahoma"},
  {abbr:"SD",name:"South Dakota"},
  {abbr:"LA",name:"Louisiana"},
  {abbr:"TX",name:"Texas"},
  {abbr:"CT",name:"Connecticut"},
  {abbr:"NH",name:"New Hampshire"},
  {abbr:"RI",name:"Rhode Island"},
  {abbr:"VT",name:"Vermont"},
  {abbr:"AL",name:"Alabama"},
  {abbr:"FL",name:"Florida"},
  {abbr:"GA",name:"Georgia"},
  {abbr:"MS",name:"Mississippi"},
  {abbr:"SC",name:"South Carolina"},
  {abbr:"IL",name:"Illinois"},
  {abbr:"IN",name:"Indiana"},
  {abbr:"KY",name:"Kentucky"},
  {abbr:"NC",name:"North Carolina"},
  {abbr:"OH",name:"Ohio"},
  {abbr:"TN",name:"Tennessee"},
  {abbr:"VA",name:"Virginia"},
  {abbr:"WI",name:"Wisconsin"},
  {abbr:"WV",name:"West Virginia"},
  {abbr:"DE",name:"Delaware"},
  {abbr:"DC",name:"District of Columbia"},
  {abbr:"MD",name:"Maryland"},
  {abbr:"NJ",name:"New Jersey"},
  {abbr:"NY",name:"New York"},
  {abbr:"PA",name:"Pennsylvania"},
  {abbr:"ME",name:"Maine"},
  {abbr:"MI",name:"Michigan"},
  {abbr:"AK",name:"Alaska"},
  {abbr:"MX",name:"Mexico"}
];
const AFGHAN_TERR = [
  {abbr:"AFBDS",name:"Badakhshan"},
  {abbr:"AFTAK",name:"Takhar"},
  {abbr:"AFKDZ",name:"Kunduz"},
  {abbr:"AFBAL",name:"Balkh"},
  {abbr:"AFJOW",name:"Jawzjan"},
  {abbr:"AFFYB",name:"Faryab"},
  {abbr:"AFBDG",name:"Badghis"},
  {abbr:"AFHER",name:"Hirat"},
  {abbr:"AFNIM",name:"Nimroz"},
  {abbr:"AFFRA",name:"Farah"},
  {abbr:"AFKNR",name:"Kunar"},
  {abbr:"AFNUR",name:"Nuristan"},
  {abbr:"AFNAN",name:"Nangarhar"},
  {abbr:"AFKHO",name:"Khost"},
  {abbr:"AFPKA",name:"Paktya"},
  {abbr:"AFPIA",name:"Paktika"},
  {abbr:"AFZAB",name:"Zabul"},
  {abbr:"AFKAN",name:"Kandahar"},
  {abbr:"AFHEL",name:"Hilmand"},
  {abbr:"AFURU",name:"Uruzgan"},
  {abbr:"AFGHA",name:"Ghazni"},
  {abbr:"AFPAN",name:"Panjshayr"},
  {abbr:"AFKAB",name:"Kabul"},
  {abbr:"AFLAG",name:"Laghman"},
  {abbr:"AFLOG",name:"Logar"},
  {abbr:"AFKAP",name:"Kapisa"},
  {abbr:"AFWAR",name:"Wardak"},
  {abbr:"AFBAM",name:"Bamyan"},
  {abbr:"AFPAR",name:"Parwan"},
  {abbr:"AFSAR",name:"Sari Pul"},
  {abbr:"AFGHO",name:"Ghor"},
  {abbr:"AFBGL",name:"Baghlan"},
  {abbr:"AFSAM",name:"Samangan"},
  {abbr:"AFDAY",name:"Daykundi"}
];
const JAMAICA_TERR = [
  {abbr:"JM06",name:"Saint Ann"},
  {abbr:"JM07",name:"Trelawny"},
  {abbr:"JM08",name:"Saint James"},
  {abbr:"JM09",name:"Hanover"},
  {abbr:"JM10",name:"Westmoreland"},
  {abbr:"JM11",name:"Saint Elizabeth"},
  {abbr:"JM12",name:"Manchester"},
  {abbr:"JM13",name:"Clarendon"},
  {abbr:"JM14",name:"Saint Catherine"},
  {abbr:"JM02",name:"Saint Andrew"},
  {abbr:"JM01",name:"Kingston"},
  {abbr:"JM03",name:"Saint Thomas"},
  {abbr:"JM04",name:"Portland"},
  {abbr:"JM05",name:"Saint Mary"}
];
const JAPAN_TERR = [
  {abbr:"JP46",name:"Kagoshima"},
  {abbr:"JP44",name:"\u014cita"},
  {abbr:"JP40",name:"Fukuoka"},
  {abbr:"JP41",name:"Saga"},
  {abbr:"JP42",name:"Nagasaki"},
  {abbr:"JP43",name:"Kumamoto"},
  {abbr:"JP45",name:"Miyazaki"},
  {abbr:"JP36",name:"Tokushima"},
  {abbr:"JP37",name:"Kagawa"},
  {abbr:"JP38",name:"Ehime"},
  {abbr:"JP39",name:"K\u014dchi"},
  {abbr:"JP32",name:"Shimane"},
  {abbr:"JP35",name:"Yamaguchi"},
  {abbr:"JP31",name:"Tottori"},
  {abbr:"JP28",name:"Hy\u014dgo"},
  {abbr:"JP26",name:"Ky\u014dto"},
  {abbr:"JP18",name:"Fukui"},
  {abbr:"JP17",name:"Ishikawa"},
  {abbr:"JP16",name:"Toyama"},
  {abbr:"JP15",name:"Niigata"},
  {abbr:"JP06",name:"Yamagata"},
  {abbr:"JP05",name:"Akita"},
  {abbr:"JP02",name:"Aomori"},
  {abbr:"JP03",name:"Iwate"},
  {abbr:"JP04",name:"Miyagi"},
  {abbr:"JP07",name:"Fukushima"},
  {abbr:"JP08",name:"Ibaraki"},
  {abbr:"JP12",name:"Chiba"},
  {abbr:"JP13",name:"Tokyo"},
  {abbr:"JP14",name:"Kanagawa"},
  {abbr:"JP22",name:"Shizuoka"},
  {abbr:"JP23",name:"Aichi"},
  {abbr:"JP24",name:"Mie"},
  {abbr:"JP30",name:"Wakayama"},
  {abbr:"JP27",name:"\u014csaka"},
  {abbr:"JP33",name:"Okayama"},
  {abbr:"JP34",name:"Hiroshima"},
  {abbr:"JP01",name:"Hokkaid\u014d"},
  {abbr:"JP47",name:"Okinawa"},
  {abbr:"JP10",name:"Gunma"},
  {abbr:"JP20",name:"Nagano"},
  {abbr:"JP09",name:"Tochigi"},
  {abbr:"JP21",name:"Gifu"},
  {abbr:"JP25",name:"Shiga"},
  {abbr:"JP11",name:"Saitama"},
  {abbr:"JP19",name:"Yamanashi"},
  {abbr:"JP29",name:"Nara"}
];
const JAMAICA_ADJ = {
  "JM09":["JM08","JM10"],
  "JM08":["JM09","JM07","JM10"],
  "JM07":["JM08","JM06","JM11","JM12"],
  "JM06":["JM07","JM05","JM12","JM13"],
  "JM10":["JM09","JM08","JM11"],
  "JM11":["JM10","JM07","JM12"],
  "JM12":["JM11","JM07","JM06","JM13"],
  "JM13":["JM12","JM06","JM14"],
  "JM14":["JM13","JM05","JM02"],
  "JM05":["JM06","JM14","JM02","JM04"],
  "JM02":["JM14","JM05","JM01","JM04","JM03"],
  "JM01":["JM02"],
  "JM03":["JM02","JM04"],
  "JM04":["JM05","JM02","JM03"]
};
const AFGHAN_ADJ = {
  "AFBDS":["AFTAK","AFNUR"],
  "AFTAK":["AFBDS","AFKDZ","AFBGL","AFNUR"],
  "AFKDZ":["AFTAK","AFBAL","AFBGL"],
  "AFBAL":["AFKDZ","AFJOW","AFSAM","AFBGL"],
  "AFJOW":["AFBAL","AFFYB","AFSAR"],
  "AFFYB":["AFJOW","AFBDG","AFSAR","AFGHO"],
  "AFBDG":["AFFYB","AFHER","AFGHO"],
  "AFHER":["AFBDG","AFFRA","AFGHO"],
  "AFFRA":["AFHER","AFNIM","AFHEL","AFGHO"],
  "AFNIM":["AFFRA","AFHEL","AFKAN"],
  "AFHEL":["AFFRA","AFNIM","AFKAN","AFURU","AFGHO","AFDAY"],
  "AFKAN":["AFNIM","AFHEL","AFZAB"],
  "AFZAB":["AFKAN","AFURU","AFGHA","AFPIA"],
  "AFURU":["AFHEL","AFZAB","AFGHA","AFDAY","AFGHO"],
  "AFDAY":["AFGHO","AFHEL","AFURU","AFBAM"],
  "AFGHO":["AFFYB","AFBDG","AFHER","AFFRA","AFHEL","AFURU","AFDAY","AFBAM","AFSAR"],
  "AFSAR":["AFJOW","AFFYB","AFGHO","AFBAM","AFSAM"],
  "AFSAM":["AFBAL","AFSAR","AFBAM","AFBGL"],
  "AFBAM":["AFSAR","AFSAM","AFGHO","AFDAY","AFWAR","AFPAR","AFBGL"],
  "AFBGL":["AFTAK","AFKDZ","AFBAL","AFSAM","AFBAM","AFPAR","AFPAN"],
  "AFPAR":["AFBAM","AFBGL","AFPAN","AFKAB","AFWAR","AFKAP"],
  "AFPAN":["AFBGL","AFPAR","AFKAP","AFNUR"],
  "AFNUR":["AFBDS","AFTAK","AFPAN","AFLAG","AFKNR"],
  "AFKNR":["AFNUR","AFLAG","AFNAN"],
  "AFLAG":["AFNUR","AFKNR","AFNAN","AFKAP","AFKAB"],
  "AFKAP":["AFPAN","AFPAR","AFLAG","AFKAB"],
  "AFKAB":["AFPAR","AFKAP","AFLAG","AFLOG","AFWAR"],
  "AFLOG":["AFKAB","AFWAR","AFGHA","AFPKA"],
  "AFWAR":["AFBAM","AFPAR","AFKAB","AFLOG","AFGHA"],
  "AFGHA":["AFWAR","AFLOG","AFPKA","AFPIA","AFZAB","AFURU"],
  "AFPKA":["AFLOG","AFGHA","AFKHO","AFPIA"],
  "AFKHO":["AFPKA","AFNAN","AFPIA"],
  "AFNAN":["AFKNR","AFLAG","AFKHO","AFPKA"],
  "AFPIA":["AFPKA","AFKHO","AFGHA","AFZAB"]
};
const JAPAN_ADJ = {
  "JP01":["JP02"],
  "JP02":["JP01","JP05","JP03"],
  "JP03":["JP02","JP05","JP04"],
  "JP04":["JP03","JP05","JP06","JP07"],
  "JP05":["JP02","JP03","JP04","JP06"],
  "JP06":["JP05","JP04","JP07"],
  "JP07":["JP06","JP04","JP08","JP09","JP10","JP15"],
  "JP08":["JP07","JP09","JP11","JP12"],
  "JP09":["JP07","JP08","JP10","JP11"],
  "JP10":["JP07","JP09","JP11","JP15","JP20"],
  "JP11":["JP08","JP09","JP10","JP12","JP13","JP14","JP19"],
  "JP12":["JP08","JP11","JP13"],
  "JP13":["JP11","JP12","JP14"],
  "JP14":["JP11","JP13","JP19","JP22"],
  "JP15":["JP07","JP10","JP16","JP20"],
  "JP16":["JP15","JP17","JP20","JP21"],
  "JP17":["JP16","JP18"],
  "JP18":["JP17","JP21","JP25","JP26"],
  "JP19":["JP11","JP14","JP20","JP22"],
  "JP20":["JP10","JP15","JP16","JP19","JP21","JP22","JP23"],
  "JP21":["JP16","JP18","JP20","JP23","JP24","JP25"],
  "JP22":["JP14","JP19","JP20","JP23"],
  "JP23":["JP20","JP21","JP22","JP24"],
  "JP24":["JP21","JP23","JP25","JP26","JP29","JP30"],
  "JP25":["JP18","JP21","JP24","JP26"],
  "JP26":["JP18","JP24","JP25","JP27","JP28","JP29"],
  "JP27":["JP26","JP28","JP29","JP30"],
  "JP28":["JP26","JP27","JP31","JP33"],
  "JP29":["JP24","JP26","JP27","JP30"],
  "JP30":["JP24","JP27","JP29"],
  "JP31":["JP28","JP32","JP33"],
  "JP32":["JP31","JP33","JP34","JP35"],
  "JP33":["JP28","JP31","JP32","JP34"],
  "JP34":["JP32","JP33","JP35"],
  "JP35":["JP32","JP34","JP40"],
  "JP36":["JP37","JP38","JP39"],
  "JP37":["JP36","JP38"],
  "JP38":["JP36","JP37","JP39"],
  "JP39":["JP36","JP38"],
  "JP40":["JP35","JP41","JP43","JP44"],
  "JP41":["JP40","JP42","JP43"],
  "JP42":["JP41","JP43"],
  "JP43":["JP40","JP41","JP42","JP44","JP45","JP46"],
  "JP44":["JP40","JP43","JP45"],
  "JP45":["JP43","JP44","JP46"],
  "JP46":["JP43","JP45"],
  "JP47":[]
};
const EUROPE_ADJ = {
  "IE":["GB"],
  "GB":["IE","FR"],
  "IS":[],
  "PT":["ES"],
  "ES":["PT","FR","AD"],
  "AD":["ES","FR"],
  "FR":["GB","ES","AD","BE","LU","DE","CH","IT","MC"],
  "BE":["FR","LU","DE","NL"],
  "NL":["BE","DE"],
  "LU":["FR","BE","DE"],
  "DE":["NL","BE","LU","FR","CH","AT","CZ","PL","DK"],
  "DK":["DE","SE"],
  "NO":["SE","FI"],
  "SE":["NO","FI","DK"],
  "FI":["SE","NO","RU"],
  "EE":["LV","RU"],
  "LV":["EE","LT","RU","BY"],
  "LT":["LV","PL","BY","RU"],
  "PL":["DE","CZ","SK","UA","BY","LT"],
  "CZ":["DE","PL","SK","AT"],
  "SK":["CZ","PL","UA","HU","AT"],
  "AT":["DE","CZ","SK","HU","SI","IT","CH","LI"],
  "CH":["FR","DE","AT","IT","LI"],
  "LI":["CH","AT"],
  "IT":["FR","CH","AT","SI"],
  "SI":["IT","AT","HU","HR"],
  "HU":["AT","SK","UA","RO","RS","HR","SI"],
  "HR":["SI","HU","RS","BA","ME"],
  "BA":["HR","RS","ME"],
  "RS":["HU","RO","BG","MK","XK","ME","BA","HR"],
  "ME":["HR","BA","RS","XK","AL"],
  "XK":["ME","RS","MK","AL"],
  "AL":["ME","XK","MK","GR"],
  "MK":["AL","XK","RS","BG","GR"],
  "BG":["RS","MK","GR","TR","RO"],
  "RO":["HU","RS","BG","MD","UA"],
  "MD":["RO","UA"],
  "UA":["PL","SK","HU","RO","MD","BY"],
  "BY":["PL","LT","LV","UA"],
  "GR":["AL","MK","BG","TR"],
  "TR":["GR","BG","GE","AM"],
  "GE":["TR","AM"],
  "AM":["GE","TR"],
  "CY":[]
};
const WORLD_ADJ = {
  "US":["CA","MX"],
  "CA":["US"],
  "MX":["US","GT","BZ"],
  "GT":["MX","BZ","HN","SV"],
  "BZ":["MX","GT"],
  "SV":["GT","HN"],
  "HN":["GT","SV","NI"],
  "NI":["HN","CR"],
  "CR":["NI","PA"],
  "PA":["CR","CO"],
  "CO":["PA","VE","BR","PE","EC"],
  "VE":["CO","BR","GY"],
  "GY":["VE","BR","SR"],
  "SR":["GY","BR","GF"],
  "GF":["SR","BR"],
  "EC":["CO","PE"],
  "PE":["EC","CO","BR","BO","CL"],
  "BO":["PE","BR","PY","AR","CL"],
  "PY":["BO","BR","AR"],
  "BR":["CO","VE","GY","SR","GF","PE","BO","PY","AR","UY"],
  "UY":["BR","AR"],
  "AR":["CL","BO","PY","BR","UY"],
  "CL":["PE","BO","AR"],
  "GB":["IE","FR"],
  "IE":["GB"],
  "FR":["GB","BE","LU","DE","CH","IT","ES","AD"],
  "ES":["FR","AD","PT"],
  "PT":["ES"],
  "AD":["FR","ES"],
  "BE":["FR","LU","NL","DE"],
  "NL":["BE","DE"],
  "LU":["FR","BE","DE"],
  "DE":["NL","BE","LU","FR","CH","AT","CZ","PL","DK"],
  "CH":["FR","DE","AT","IT"],
  "AT":["DE","CH","IT","SI","HU","SK","CZ"],
  "IT":["FR","CH","AT","SI"],
  "SI":["IT","AT","HU","HR"],
  "CZ":["DE","AT","SK","PL"],
  "PL":["DE","CZ","SK","UA","BY","LT","RU"],
  "SK":["CZ","AT","HU","UA","PL"],
  "HU":["AT","SK","UA","RO","RS","HR","SI"],
  "HR":["SI","HU","RS","BA","ME"],
  "BA":["HR","RS","ME"],
  "RS":["HU","RO","BG","MK","AL","ME","BA","HR"],
  "ME":["HR","BA","RS","AL"],
  "AL":["ME","RS","MK","GR"],
  "MK":["AL","RS","BG","GR"],
  "BG":["RS","MK","GR","TR","RO"],
  "RO":["HU","RS","BG","MD","UA"],
  "MD":["RO","UA"],
  "UA":["PL","SK","HU","RO","MD","BY","RU"],
  "BY":["PL","LT","LV","RU","UA"],
  "LT":["PL","BY","LV","RU"],
  "LV":["LT","EE","RU","BY"],
  "EE":["LV","RU"],
  "DK":["DE"],
  "NO":["SE","FI","RU"],
  "SE":["NO","FI"],
  "FI":["SE","NO","RU"],
  "RU":["NO","FI","EE","LV","LT","PL","BY","UA","GE","AZ","KZ","CN","MN","KP"],
  "GE":["RU","TR","AM","AZ"],
  "AM":["GE","TR","AZ","IR"],
  "AZ":["GE","AM","IR","RU"],
  "TR":["GR","BG","GE","AM","IR","IQ","SY"],
  "GR":["AL","MK","BG","TR"],
  "CY":[],
  "SY":["TR","IQ","JO","LB","IL"],
  "LB":["SY","IL"],
  "IL":["LB","SY","JO","EG"],
  "JO":["IL","SY","IQ","SA"],
  "IQ":["TR","SY","JO","SA","KW","IR"],
  "IR":["TR","IQ","AM","AZ","TM","AF","PK"],
  "KW":["IQ","SA"],
  "SA":["JO","IQ","KW","QA","AE","OM","YE"],
  "QA":["SA"],
  "AE":["SA","OM"],
  "OM":["AE","SA","YE"],
  "YE":["SA","OM"],
  "EG":["IL","LY","SD"],
  "LY":["EG","SD","TD","NE","DZ","TN"],
  "TN":["LY","DZ"],
  "DZ":["TN","LY","NE","ML","MR","MA","EH"],
  "MA":["DZ","EH"],
  "EH":["MA","DZ","MR"],
  "MR":["EH","DZ","ML","SN"],
  "ML":["MR","DZ","NE","BF","CI","GN","SN"],
  "SN":["MR","ML","GN","GW","GM"],
  "GM":["SN"],
  "GW":["SN","GN"],
  "GN":["GW","SN","ML","CI","LR","SL"],
  "SL":["GN","LR"],
  "LR":["SL","GN","CI"],
  "CI":["LR","GN","ML","BF","GH"],
  "BF":["ML","NE","BJ","TG","GH","CI"],
  "GH":["CI","BF","TG"],
  "TG":["GH","BF","BJ"],
  "BJ":["TG","BF","NE","NG"],
  "NE":["ML","DZ","LY","TD","NG","BJ","BF"],
  "NG":["BJ","NE","TD","CM"],
  "TD":["NE","LY","SD","CF","CM","NG"],
  "SD":["EG","LY","TD","CF","SS","ET","ER"],
  "SS":["SD","ET","KE","UG","CD","CF"],
  "ER":["SD","ET"],
  "ET":["ER","SD","SS","KE","SO","DJ"],
  "DJ":["ER","ET","SO"],
  "SO":["DJ","ET","KE"],
  "KE":["SO","ET","SS","UG","TZ"],
  "UG":["SS","KE","TZ","RW","CD"],
  "RW":["UG","TZ","BI","CD"],
  "BI":["RW","TZ","CD"],
  "TZ":["KE","UG","RW","BI","CD","ZM","MW","MZ"],
  "CD":["CF","SS","UG","RW","BI","TZ","ZM","AO","CG"],
  "CG":["GA","CM","CF","CD","AO"],
  "CF":["CM","TD","SD","SS","CD","CG"],
  "CM":["NG","TD","CF","CG","GA","GQ","GA"],
  "GA":["CM","GQ","CG"],
  "GQ":["CM","GA"],
  "AO":["CD","CG","ZM","NA"],
  "ZM":["AO","CD","TZ","MW","MZ","ZW","BW","NA"],
  "MW":["TZ","ZM","MZ"],
  "MZ":["TZ","MW","ZM","ZW","ZA","SZ"],
  "ZW":["ZM","MZ","ZA","BW"],
  "BW":["NA","ZM","ZW","ZA"],
  "NA":["AO","ZM","BW","ZA"],
  "ZA":["NA","BW","ZW","MZ","SZ","LS"],
  "SZ":["ZA","MZ"],
  "LS":["ZA"],
  "CN":["RU","MN","KZ","KG","TJ","AF","PK","IN","NP","BT","MM","LA","VN","KP"],
  "MN":["RU","CN"],
  "KZ":["RU","CN","KG","UZ","TM"],
  "KG":["KZ","CN","TJ","UZ"],
  "TJ":["KG","CN","AF","UZ"],
  "UZ":["KZ","KG","TJ","AF","TM"],
  "TM":["KZ","UZ","AF","IR"],
  "AF":["IR","TM","UZ","TJ","CN","PK"],
  "PK":["IR","AF","CN","IN"],
  "IN":["PK","CN","NP","BT","BD","MM"],
  "NP":["IN","CN"],
  "BT":["IN","CN"],
  "BD":["IN","MM"],
  "MM":["BD","IN","CN","LA","TH"],
  "LA":["MM","CN","VN","KH","TH"],
  "VN":["CN","LA","KH"],
  "KH":["TH","LA","VN"],
  "TH":["MM","LA","KH","MY"],
  "MY":["TH","ID","BN"],
  "ID":["MY","PG","TL"],
  "BN":["MY"],
  "TL":["ID"],
  "PG":["ID"],
  "AU":[],
  "NZ":[],
  "JP":[],
  "KR":["KP"],
  "KP":["CN","RU","KR"],
  "PH":[],
  "TW":[]
};
const NA_EXTRA_ADJ = {
  "MB":["ON","SK","NU","ND","MN"],
  "SK":["AB","MB","NT","MT","ND"],
  "AB":["BC","SK","NT","MT"],
  "BC":["AB","YT","NT","WA","AK","ID"],
  "YT":["BC","NT","AK"],
  "NT":["YT","BC","AB","SK","NU"],
  "NU":["NT","MB"],
  "ON":["MB","QC","MN","MI"],
  "QC":["ON","NL","NB","ME","NH","VT","NY"],
  "NB":["QC","NS","PE","ME"],
  "NS":["NB","PE"],
  "PE":["NB","NS"],
  "NL":["QC"],
  "MX":["TX","AZ","CA","NM"],
  "DC":["MD","VA"]
};

function naAdj(){
  const A = {};
  Object.keys(ADJ).forEach(k => A[k] = ADJ[k].slice());
  Object.keys(NA_EXTRA_ADJ).forEach(k => {
    A[k] = (A[k]||[]).concat(NA_EXTRA_ADJ[k]);
  });
  // bidirectional extras
  Object.keys(NA_EXTRA_ADJ).forEach(k => {
    NA_EXTRA_ADJ[k].forEach(n => {
      if(!A[n]) A[n]=[];
      if(!A[n].includes(k)) A[n].push(k);
    });
  });
  return A;
}

const MAP_PACKS = {
  usa: {label:'USA States', type:'usa'},
  circuit: {label:'Smash Circuit', type:'circuit'},
  world: {label:'World', type:'svg', file:'maps/world.svg', terr:WORLD_TERR, adj:WORLD_ADJ},
  europe: {label:'Europe', type:'svg', file:'maps/europe.svg', terr:EUROPE_TERR, adj:EUROPE_ADJ},
  na: {label:'North America', type:'svg', file:'maps/north-america.svg', terr:NA_TERR, adj:null},
  japan: {label:'Japan Prefectures', type:'svg', file:'maps/japan.svg', terr:JAPAN_TERR, adj:JAPAN_ADJ},
  jamaica: {label:'Jamaica Parishes', type:'svg', file:'maps/jamaica.svg', terr:JAMAICA_TERR, adj:JAMAICA_ADJ},
  afghanistan: {label:'Afghanistan Provinces', type:'svg', file:'maps/afghanistan.svg', terr:AFGHAN_TERR, adj:AFGHAN_ADJ}
};
